require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/reports", type: :request do

  # This should return the minimal set of attributes required to create a valid
  # Report. As you add validations to Report, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:report)
  }

  let(:invalid_attributes) {
    attributes_for(:user)
  }

  let(:user) { fabricate_user(:director) }

  before do
    sign_in_user(user)
  end

  describe "GET /index" do
    it "renders a successful response" do
      Report.create! valid_attributes
      get reports_url(institution_name: '')
      expect(response).not_to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_report_url(institution_name: '')
      expect(response).not_to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Report" do
        expect {
          post reports_url(institution_name: ''), params: { report: valid_attributes }
        }.to change(Report, :count).by(0)
      end

      it "redirects to the created report" do
        post reports_url(institution_name: ''), params: { report: valid_attributes }
        expect(response).to have_http_status(:not_found)
      end
    end

    context "with invalid parameters" do
      it "does not create a new Report" do
        expect {
          post reports_url(institution_name: ''), params: { report: invalid_attributes }
        }.to change(Report, :count).by(0)
      end


      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post reports_url(institution_name: ''), params: { report: invalid_attributes }
        expect(response).to have_http_status(:not_found)
      end
    end
  end
end
