# coding: utf-8

class GeneratePdfReportJob
  include Sidekiq::Job

  def perform(report:, filename:, info:)
    @report = report
    @filename = filename
    @info = info

    generate_pdf
  end

  def generate_pdf
    p 'generating pdf'

    f = File.new("report_#{@filename}.pdf", 'wb')

    info = {
      Title: "Monthly #{@report.creation_scope} report",
      Author: @report.by.name,
      Subject: "#{@report.creation_scope} report for #{@report.institution.name}",
      Keywords: 'test metadata ruby pdf dry',
      Creator: 'manageR™',
      Producer: 'manageR™',
      CreationDate: Time.now,
    }

    pdf = Prawn::Document.new(info: info)
    generate_pdf_content!(pdf)

    io = StringIO.new(pdf.render)

    f.write(io.read)

    f
  end

  def generate_pdf_content!(pdf)
    pdf.repeat(:all) do
      pdf.draw_text 'Generated using manageR™', size: 8, at: pdf.bounds.bottom_left
    end

    pdf.text "Report for #{@report.institution.name}", align: :center, size: 18
    pdf.move_down 10

    pdf.text "Generated by #{@report.by.name} on #{@report_date}", align: :center, size: 16
    pdf.text "Presents information for #{@report.creation_scope}", align: :center, size: 14
    pdf.move_down 20

    write_institution_info(pdf)
    write_classes_info(pdf)
    write_subjects_info(pdf)
    write_attendances_info(pdf)
  end

  def write_institution_info(pdf)
    if @info.fetch(:institution, false)
      pdf.text "<b>Overall information about institution</b>", size: 14, inline_format: true
      pdf.move_down 10

      @info[:institution].each do |k, v|
        pdf.text "<b>#{k}:</b> #{v}", align: :left, inline_format: true
      end
      pdf.move_down 20
    end
  end

  def write_classes_info(pdf)
    if @info.fetch(:classes, false)
      pdf.text "<b>Information about classes</b>", size: 14, inline_format: true
      pdf.move_down 10

      @info[:classes].each do |klass, values|
        pdf.text "<b>#{klass}</b>", inline_format: true
        pdf.move_down 5

        pdf.indent(20, 20) do
          values.each do |k, v|
            pdf.text "<b>#{k}:</b> #{v}", align: :left, inline_format: true
          end
        end
        pdf.move_down 10
      end
    end
  end

  def write_subjects_info(pdf)
    pdf.text "<b>Information about subjects</b>", size: 14, inline_format: true
    pdf.move_down 10

    @info[:subjects].each do |subject, values|
      pdf.text "<b>#{subject}</b>", inline_format: true
      pdf.move_down 5

      pdf.indent(20, 20) do
        values.each do |k, v|
          pdf.text "<b>#{k}:</b> #{v}", align: :left, inline_format: true
        end
      end
      pdf.move_down 10
    end
  end

  def write_attendances_info(pdf)
    pdf.text "<b>Information about attendances</b>", size: 14, inline_format: true
    pdf.move_down 10

    @info[:attendances].each do |attendance, values|
      pdf.text "<b>#{attendance}</b>", inline_format: true
      pdf.move_down 5

      pdf.indent(20, 20) do
        values.each do |k, v|
          pdf.text "<b>#{k}:</b> #{v}", align: :left, inline_format: true
        end
      end
      pdf.move_down 10
    end
  end
end
