class User < ApplicationRecord
  # Signing up for the system is disabled.
  # Only system/institution admins can create new users, BUT
  # :registerable needs to stay here due to the need for edit_registration
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :institution
  belongs_to :i_class

  enum access_type: {
         admin: 5,
         director: 4,
         teacher: 3,
         student: 2,
         unassigned: 0,
       }

  mount_uploader :image, ImageUploader

  validates :access_type, presence: true, inclusion: { in: :access_type }

  scope :users_visible_to_me, ->(access_types) { where(access_type: access_types)}

  scope :access_visible_to, ->(user) {
    visible = %w[student]
    visible << %w[teacher director] if user.teacher? || user.director? || user.admin?
    visible << 'admin' if user.admin?

    visible.flatten
  }

  def has_elevated_privileges?
    admin? || director?
  end

  # generated by AA
  def self.ransackable_attributes(auth_object = nil)
    %w[access_type created_at email encrypted_password gender id image name phone remember_created_at reset_password_sent_at reset_password_token updated_at institution]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[institution]
  end
end
